// ATRIBUTOS DAS CLASSES
const atributos = {
  Barbarian: {
    principal: 'constituicao',
    forca: 3,
    destreza: 2,
    constituicao: 3,
    inteligencia: 1,
    sabedoria: 2,
    carisma: 2,
  },
  Cleric: {
    principal: 'carisma',
    forca: 2,
    destreza: 1,
    constituicao: 2,
    inteligencia: 3,
    sabedoria: 2,
    carisma: 3,
  },
  Druid: {
    principal: 'sabedoria',
    forca: 2,
    destreza: 2,
    constituicao: 3,
    inteligencia: 2,
    sabedoria: 3,
    carisma: 1,
  },
  Fighter: {
    principal: 'forca',
    forca: 3,
    destreza: 2,
    constituicao: 3,
    inteligencia: 1,
    sabedoria: 2,
    carisma: 2,
  },
  Monk: {
    principal: 'destreza',
    forca: 3,
    destreza: 3,
    constituicao: 2,
    inteligencia: 1,
    sabedoria: 2,
    carisma: 2,
  },
  Paladin: {
    principal: 'forca',
    forca: 3,
    destreza: 2,
    constituicao: 2,
    inteligencia: 1,
    sabedoria: 2,
    carisma: 3,
  },
  Ranger: {
    principal: 'constituicao',
    forca: 2,
    destreza: 3,
    constituicao: 3,
    inteligencia: 1,
    sabedoria: 2,
    carisma: 2,
  },
  Rogue: {
    principal: 'destreza',
    forca: 2,
    destreza: 3,
    constituicao: 2,
    inteligencia: 1,
    sabedoria: 2,
    carisma: 3,
  },
  Sorcerer: {
    principal: 'sabedoria',
    forca: 2,
    destreza: 2,
    constituicao: 2,
    inteligencia: 3,
    sabedoria: 3,
    carisma: 1,
  },
  Warlock: {
    principal: 'inteligencia',
    forca: 1,
    destreza: 2,
    constituicao: 2,
    inteligencia: 3,
    sabedoria: 3,
    carisma: 2,
  },
  Wizard: {
    principal: 'inteligencia',
    forca: 1,
    destreza: 2,
    constituicao: 2,
    inteligencia: 3,
    sabedoria: 2,
    carisma: 3,
  },
};
// FICHA EM BRANCO
// classeDeArmadura = 10 + constituição!
// seu atributo atual acrescenta o valor dele a proficiencia!
const fichaEmBranco = {
  nome: '',
  vidaMaxima: 0,
  vida: 0,
  mana: 3,
  raça: 'humanoide',
  classe: '',
  dadoDeVida: '',
  classeDeArmadura: 0,
  proficiencia: 1,
  atributos: {
    principal: '',
    forca: 0,
    destreza: 0,
    constituicao: 0,
    inteligencia: 0,
    sabedoria: 0,
    carisma: 0,
  },
  skills: {
    ataqueBasico: true,
    truque: 0,
    habilidade: 0,
  },
};

export { fichaEmBranco, atributos };
